version: '3.8'
services:
  # 1. DataBase Container (SQL Server)
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: retail_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MyPass123 # SSMS Password
    ports:
      - "1433:1433"
    volumes:
      - D:/Retail_Project/Dataset:/dataset
      - mssql_data:/var/opt/mssql/data
